apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.28.0 (HEAD)
  labels:
    io.kompose.service: kafka-ui
  name: kafka-ui
  namespace: develop
spec:
  ports:
    - name: "9020"
      port: 9020
      targetPort: 8080
  selector:
    io.kompose.service: kafka-ui
status:
  loadBalancer: {}
