kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: develop-media-efs-sc
provisioner: efs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  provisioningMode: efs-ap
  fileSystemId: [FILESYSTEM-ID]
  directoryPerms: "700"
